EliziumWeb/Models/ErrorViewModel.cs
using System;

namespace EliziumWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EliziumWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EliziumWeb.Models;
using System.IO;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EliziumWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EliziumWeb/Controllers/StatController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EliziumWeb.Controllers
{
    public class StatController : Controller
    {
        private readonly IOptions<AppSettings> config;

        public StatController(IOptions<AppSettings> config)
        {
            this.config = config;
        }

        [ResponseCache(Duration = 10, Location = ResponseCacheLocation.Any, NoStore = false)]
        public ActionResult Details(string id, string name)
        {
            JObject data = null;

            var f = config.Value.StatFolder;

            var file = new FileInfo($"{f}/{id}.json");
            if (!file.Exists)
                return NotFound();

            using (StreamReader jf = file.OpenText())
            {
                using (JsonTextReader reader = new JsonTextReader(jf))
                {
                    data = (JObject)JToken.ReadFrom(reader);
                }
            }

            ViewBag.UserName = name;

            return PartialView(data);
        }
    }
}

EliziumWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Статистика";
}

<link rel="stylesheet" href="~/css/blocks_items.css" />

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <p>
        @Html.ActionLink("SomeUser", "Details", "Stat", new { id = "0b9c2cba-836d-3f7d-81a5-3b589a890a56", name = "SomeUser" })
    </p>
    <p>
        @Html.ActionLink("OtherUser", "Details", "Stat", new { id = "0b945540-e168-3c20-9b27-3427099d8c95", name = "OtherUser" })
    </p>

</div>

EliziumWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EliziumWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EliziumWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - EliziumWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

EliziumWeb/Views/Stat/Details.cshtml
@using Newtonsoft.Json.Linq
@model JObject

@{
var iPickDiamond = ((JObject)Model["stats"]["minecraft:picked_up"]).Property("minecraft:diamond");
var iDroppedDiamond = ((JObject)Model["stats"]["minecraft:dropped"]).Property("minecraft:diamond");
var iPickIron = ((JObject)Model["stats"]["minecraft:picked_up"]).Property("minecraft:iron_ingot");
var iDroppedIron = ((JObject)Model["stats"]["minecraft:dropped"]).Property("minecraft:iron_ingot");

var iDestroyStone = ((JObject)Model["stats"]["minecraft:mined"]).Property("minecraft:stone");
var iDestroyIron = ((JObject)Model["stats"]["minecraft:mined"]).Property("minecraft:iron_ore");

var KillMob = ((JObject)Model["stats"]["minecraft:custom"]).Property("minecraft:mob_kills");
var PlayerKill = ((JObject)Model["stats"]["minecraft:custom"]).Property("minecraft:player_kills");
var deaths = ((JObject)Model["stats"]["minecraft:custom"]).Property("minecraft:deaths");
var PlayTime = ((JObject)Model["stats"]["minecraft:custom"]).Property("minecraft:play_one_minute");
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-md-10">
			<div class="card bg-light mb-3">
				<div class="card-header"><h5>Основная</h5></div>
				<div class="card-body">
					<div class="row justify-content-start">
						<div class="col col-auto">
							<h6>Время в игре <span class="badge badge-secondary">@PlayTime?.Value</span> мин.</h6>
						</div>
						<div class="col col-auto">
							<h6>Смертей <span class="badge badge-secondary">@deaths?.Value</span></h6>
						</div>
						<div class="col col-auto">
							<h6>Убил игроков <span class="badge badge-secondary">@PlayerKill?.Value</span></h6>
						</div>
						<div class="col col-auto">
							<h6>Убил мобов <span class="badge badge-secondary">@KillMob?.Value</span></h6>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card bg-light mb-3" style="max-width: 30rem;">
				<div class="card-header"><h5>Предметы</h5></div>
				<div class="card-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col">Предмет</th>
								<th scope="col">Подобрал</th>
								<th scope="col">Выбросил</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<abbr title="Алмаз"><span class="item diamond img-thumbnail"></span></abbr>
								</td>
								<td>@iPickDiamond?.Value</td>
								<td>@iDroppedDiamond?.Value</td>
							</tr>
							<tr>
								<td>
									<abbr title="Слиток железа"><span class="item iron_ingot img-thumbnail"></span></abbr>
								</td>
								<td>@iPickIron?.Value</td>
								<td>@iDroppedIron?.Value</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col col-md-4">
			<div class="card bg-light mb-3" style="max-width: 20rem;">
				<div class="card-header"><h5>Блоки</h5></div>
				<div class="card-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col">Блок</th>
								<th scope="col">Выкопал</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<abbr title="Камень"><span class="item stone img-thumbnail"></span></abbr>
								</td>
								<td>@iDestroyStone?.Value</td>
							</tr>
							<tr>
								<td>
									<abbr title="Железная руда"><span class="item iron_ore img-thumbnail"></span></abbr>
								</td>
								<td>@iDestroyIron?.Value</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
}